table _TOOLTIP_DIM_MOVIES
	lineageTag: 3b570e6c-1232-440f-9910-7601c871eb16

	measure 'Tooltip Movie Count' =
			
			VAR SelectedYears =
			    VALUES(DIM_MOVIES[Year])
			
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT(_TOOLTIP_DIM_MOVIES[MOVIE_ID]),
			        TREATAS(
			            SelectedYears,
			            _TOOLTIP_DIM_MOVIES[Year]
			        )
			    )
		formatString: 0
		lineageTag: fe06436e-6754-4822-b2d7-8572d7e7531f

	column MOVIE_ID
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 7f72e905-5637-4bb0-b0bf-f0c378b21501
		summarizeBy: none
		sourceColumn: MOVIE_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TITLE
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 1b69cd28-e067-4c32-bb20-b61b3be64307
		summarizeBy: none
		sourceColumn: TITLE

		annotation SummarizationSetBy = Automatic

	column ORIGINAL_TITLE
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: f4081ddc-73af-4234-96ec-19dbbe700e91
		summarizeBy: none
		sourceColumn: ORIGINAL_TITLE

		annotation SummarizationSetBy = Automatic

	column RELEASE_DATE
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: e8e969d4-2016-4b19-89db-74e88e9e77fb
		summarizeBy: none
		sourceColumn: RELEASE_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ORIGINAL_LANGUAGE
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: b3d349af-4440-4e1e-bd44-f8306d9104e3
		summarizeBy: none
		sourceColumn: ORIGINAL_LANGUAGE

		annotation SummarizationSetBy = Automatic

	column ADULT
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: c286ce30-cd54-422a-9a5e-344887a07676
		summarizeBy: none
		sourceColumn: ADULT

		annotation SummarizationSetBy = Automatic

	column BUDGET
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 7d7ef591-27f3-4256-b908-de4c8eb69c09
		summarizeBy: none
		sourceColumn: BUDGET

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RUNTIME
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 4ffbf172-6900-436b-b672-fab91150bb54
		summarizeBy: none
		sourceColumn: RUNTIME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POPULARITY
		dataType: double
		sourceProviderType: double
		lineageTag: 54131b09-8f48-4c78-a333-03526ff64fcd
		summarizeBy: none
		sourceColumn: POPULARITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVERAGE_RATING
		dataType: double
		sourceProviderType: double
		lineageTag: 32ef1897-dcdf-4c7d-a29f-6713f5375fcc
		summarizeBy: none
		sourceColumn: AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_COUNT
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 515962b6-01e1-4e5e-8c39-a60e05c9837e
		summarizeBy: none
		sourceColumn: RATING_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: f170c33a-7bf8-4d45-b3d1-b99839a3e9f4
		summarizeBy: none
		sourceColumn: REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_POPULARITY
		dataType: double
		sourceProviderType: double
		lineageTag: ac05ae7e-a2a8-4c0c-9644-103b05fdc0b7
		summarizeBy: none
		sourceColumn: FIRST_POPULARITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_AVERAGE_RATING
		dataType: double
		sourceProviderType: double
		lineageTag: f5465d39-18ab-45d8-b558-1df4b370ec81
		summarizeBy: none
		sourceColumn: FIRST_AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_RATING_COUNT
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 86887ab7-dd75-47ab-9077-58d26eebd4ea
		summarizeBy: none
		sourceColumn: FIRST_RATING_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_REVENUE
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 573fd6fd-3eeb-45fa-8c2a-5256b3d42f75
		summarizeBy: none
		sourceColumn: FIRST_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_POPULARITY
		dataType: double
		sourceProviderType: double
		lineageTag: f4a9ecb2-daf4-4120-a932-7dc609dd1a38
		summarizeBy: none
		sourceColumn: PREVIOUS_POPULARITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_AVERAGE_RATING
		dataType: double
		sourceProviderType: double
		lineageTag: 972b8940-4c7f-4a37-a65e-532d98f769ca
		summarizeBy: none
		sourceColumn: PREVIOUS_AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_RATING_COUNT
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 455af498-6ada-468e-a5f9-8ad747f2021c
		summarizeBy: none
		sourceColumn: PREVIOUS_RATING_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_REVENUE
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 77536861-8de5-4201-b06f-98896514c0c9
		summarizeBy: none
		sourceColumn: PREVIOUS_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POPULARITY_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: double
		lineageTag: 282e0baf-5743-40d6-aff5-8283b4bb40c3
		summarizeBy: none
		sourceColumn: POPULARITY_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVERAGE_RATING_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: double
		lineageTag: 61c196f5-20d5-4fd4-b2cd-67867802b898
		summarizeBy: none
		sourceColumn: AVERAGE_RATING_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_COUNT_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: f8681e8c-0c25-4a60-9c90-a48f585c9e94
		summarizeBy: none
		sourceColumn: RATING_COUNT_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 3ddef577-668c-4ac9-b0df-ba320e1d3490
		summarizeBy: none
		sourceColumn: REVENUE_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POPULARITY_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: double
		lineageTag: 8b96a376-9747-492f-b30e-3da043c62e2a
		summarizeBy: none
		sourceColumn: POPULARITY_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVERAGE_RATING_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: double
		lineageTag: 3c20a3f0-6d4a-4534-a1d5-5dac2b692a70
		summarizeBy: none
		sourceColumn: AVERAGE_RATING_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_COUNT_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: bc2ee6dc-188d-44db-bcfa-912f33cdfa56
		summarizeBy: none
		sourceColumn: RATING_COUNT_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: ae8139dd-0ea9-484d-945d-1fac3ee474a7
		summarizeBy: none
		sourceColumn: REVENUE_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LOADED_AT
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 89aed565-c454-4ffd-8a95-1736b8f2e5a9
		summarizeBy: none
		sourceColumn: LOADED_AT

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 554fb81a-cc18-4d86-8d6e-4d76751751ff
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'year flag'
		dataType: string
		lineageTag: f526202f-24f7-47fe-a502-2218d23e7a81
		summarizeBy: none
		sourceColumn: year flag

		annotation SummarizationSetBy = Automatic

	partition _TOOLTIP_DIM_MOVIES = m
		mode: directQuery
		source = ```
				let
				    Source = Snowflake.Databases("GFVHJLE-HK92660.snowflakecomputing.com","STREAMSIGHT_WH",[Implementation="2.0"]),
				    STREAMSIGHT_Database = Source{[Name="STREAMSIGHT",Kind="Database"]}[Data],
				    PROD_MARTS_Schema = STREAMSIGHT_Database{[Name="PROD_MARTS",Kind="Schema"]}[Data],
				    DIM_MOVIES_Table = PROD_MARTS_Schema{[Name="DIM_MOVIES",Kind="Table"]}[Data],
				    #"Inserted Year" = Table.AddColumn(DIM_MOVIES_Table, "Year", each Date.Year([RELEASE_DATE]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Year", "year flag", each if [Year]>=(Date.Year(DateTime.LocalNow())-10) 
				and [Year]<= Date.Year(DateTime.LocalNow()) then "Y"
				else "N")
				in
				    #"Added Custom"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

