table DIM_MOVIES
	lineageTag: a50b6b30-4558-4ef2-8351-b35bd1ae8175

	measure 'Movie Score' =
			
			VAR RatingScore =
			    DIVIDE(
			        MAX(DIM_MOVIES[AVERAGE_RATING]),
			        10
			    )
			
			VAR PopularityScore =
			    DIVIDE(
			        MAX(DIM_MOVIES[POPULARITY]),
			        CALCULATE(
			            MAX(DIM_MOVIES[POPULARITY]),
			            ALL(DIM_MOVIES)
			        )
			    )
			
			VAR RatingCountScore =
			    DIVIDE(
			        LOG(1 + MAX(DIM_MOVIES[RATING_COUNT])),
			        CALCULATE(
			            MAXX(
			                ALL(DIM_MOVIES),
			                LOG(1 + DIM_MOVIES[RATING_COUNT])
			            )
			        )
			    )
			
			RETURN
			    RatingScore * 0.45
			    + PopularityScore * 0.35
			    + RatingCountScore * 0.20
		lineageTag: 51b14f27-41f1-4c71-ae64-8c7b5f7cb665

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Movie Rank' =
			
			RANKX(
			    ALLSELECTED(DIM_MOVIES[MOVIE_ID]),
			    [Movie Score],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: 3c642361-6b1a-49d8-8c60-b65442e9a3a0

	measure 'Gross Earnings' = max(DIM_MOVIES[REVENUE])-max(DIM_MOVIES[BUDGET])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ab6ceda8-06d4-437d-ae86-bff76ade0e1d

	column MOVIE_ID
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 64a780da-21ab-4585-b778-1c43ab88fbc2
		summarizeBy: none
		sourceColumn: MOVIE_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TITLE
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 4605a8b8-7eda-49a0-bd5d-0ca6eb32d802
		summarizeBy: none
		sourceColumn: TITLE

		annotation SummarizationSetBy = Automatic

	column ORIGINAL_TITLE
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 0ecc473f-df25-4b82-9ec1-25bc78b9fcb3
		summarizeBy: none
		sourceColumn: ORIGINAL_TITLE

		annotation SummarizationSetBy = Automatic

	column RELEASE_DATE
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 396f4859-a0e7-450d-aab8-c25361ce495f
		summarizeBy: none
		sourceColumn: RELEASE_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ORIGINAL_LANGUAGE
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: b86e048a-3855-4c5d-bf69-894e7d70edb4
		summarizeBy: none
		sourceColumn: ORIGINAL_LANGUAGE

		annotation SummarizationSetBy = Automatic

	column ADULT
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 6413c97b-d78a-4a91-b372-fe42dd551546
		summarizeBy: none
		sourceColumn: ADULT

		annotation SummarizationSetBy = Automatic

	column POPULARITY
		dataType: double
		sourceProviderType: double
		lineageTag: cb46f880-5195-456e-8fb3-088066b8b6c5
		summarizeBy: sum
		sourceColumn: POPULARITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVERAGE_RATING
		dataType: double
		sourceProviderType: double
		lineageTag: ee885ca5-fff7-44d2-a6aa-96cfcec451b8
		summarizeBy: sum
		sourceColumn: AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_COUNT
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 0e88e7bf-27da-4da5-b652-294a49eefcb5
		summarizeBy: sum
		sourceColumn: RATING_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_POPULARITY
		dataType: double
		sourceProviderType: double
		lineageTag: bcb6fedd-339c-4c21-87ed-2693ebaa742f
		summarizeBy: sum
		sourceColumn: FIRST_POPULARITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_AVERAGE_RATING
		dataType: double
		sourceProviderType: double
		lineageTag: 9c1ea475-cc5f-4816-be21-b580bf3ecb43
		summarizeBy: sum
		sourceColumn: FIRST_AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_RATING_COUNT
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 890a29c2-f0d4-433c-9d97-f7637d8913c1
		summarizeBy: sum
		sourceColumn: FIRST_RATING_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_POPULARITY
		dataType: double
		sourceProviderType: double
		lineageTag: 57f643d2-27c8-446c-a478-9e50ddeef080
		summarizeBy: sum
		sourceColumn: PREVIOUS_POPULARITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_AVERAGE_RATING
		dataType: double
		sourceProviderType: double
		lineageTag: b1dfcddf-9ed2-4b9e-ac93-76ac381b8af6
		summarizeBy: sum
		sourceColumn: PREVIOUS_AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_RATING_COUNT
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: c4aed29d-8132-45de-b0d4-96ed69af6396
		summarizeBy: sum
		sourceColumn: PREVIOUS_RATING_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POPULARITY_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: double
		lineageTag: ba48a999-74bf-4a78-bf64-41c57c61b366
		summarizeBy: sum
		sourceColumn: POPULARITY_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVERAGE_RATING_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: double
		lineageTag: 6c22987c-31d5-4a51-a865-c264ba50752f
		summarizeBy: sum
		sourceColumn: AVERAGE_RATING_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_COUNT_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 5b7ef91b-9044-4298-8225-a809f53c9957
		summarizeBy: sum
		sourceColumn: RATING_COUNT_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POPULARITY_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: double
		lineageTag: a59e6037-b248-473b-86f0-f3a745fe1f4a
		summarizeBy: sum
		sourceColumn: POPULARITY_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVERAGE_RATING_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: double
		lineageTag: 81d7c0ea-717f-4eac-9707-4c418bcd1fc6
		summarizeBy: sum
		sourceColumn: AVERAGE_RATING_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_COUNT_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 4c220809-e049-457d-bd78-0ee0dbada0ce
		summarizeBy: sum
		sourceColumn: RATING_COUNT_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LOADED_AT
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: e07ba021-3060-4c53-bcc5-abc37361847f
		summarizeBy: none
		sourceColumn: LOADED_AT

		annotation SummarizationSetBy = Automatic

	column BUDGET
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: c59fdb9c-d259-486b-85d4-fa046e86023f
		summarizeBy: sum
		sourceColumn: BUDGET

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RUNTIME
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 2f8238cc-5b8d-44d6-bc0c-4be51ee4a2bb
		summarizeBy: sum
		sourceColumn: RUNTIME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 77c63a12-c5f5-4210-85d7-6c0c61174bb9
		summarizeBy: sum
		sourceColumn: REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FIRST_REVENUE
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: a3c442ad-3bc0-47ee-bbe0-f7c55850c6ee
		summarizeBy: sum
		sourceColumn: FIRST_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PREVIOUS_REVENUE
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 4085861c-721a-4c8a-af07-b051700f3ecd
		summarizeBy: sum
		sourceColumn: PREVIOUS_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE_CHANGE_SINCE_FIRST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 18a99540-601e-4d8e-b31d-f59812b4e204
		summarizeBy: sum
		sourceColumn: REVENUE_CHANGE_SINCE_FIRST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REVENUE_CHANGE_SINCE_LAST
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: 62396dd4-eae3-49b1-a53f-1fe97ce61a0d
		summarizeBy: sum
		sourceColumn: REVENUE_CHANGE_SINCE_LAST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3654ade3-ea2b-42ce-ae1a-a325908ead66
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'year flag'
		dataType: string
		lineageTag: ed72a566-7537-4c55-a622-e7a4dc3d308c
		summarizeBy: none
		sourceColumn: year flag

		annotation SummarizationSetBy = Automatic

	partition DIM_MOVIES = m
		mode: directQuery
		source = ```
				let
				    Source = Snowflake.Databases("GFVHJLE-HK92660.snowflakecomputing.com","STREAMSIGHT_WH",[Implementation="2.0"]),
				    STREAMSIGHT_Database = Source{[Name="STREAMSIGHT",Kind="Database"]}[Data],
				    PROD_MARTS_Schema = STREAMSIGHT_Database{[Name="PROD_MARTS",Kind="Schema"]}[Data],
				    DIM_MOVIES_Table = PROD_MARTS_Schema{[Name="DIM_MOVIES",Kind="Table"]}[Data],
				    #"Inserted Year" = Table.AddColumn(DIM_MOVIES_Table, "Year", each Date.Year([RELEASE_DATE]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Year", "year flag", each if [Year]>=(Date.Year(DateTime.LocalNow())-10) 
				and [Year]<= Date.Year(DateTime.LocalNow()) then "Y"
				else "N")
				in
				    #"Added Custom"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

