name: StreamSight Pipeline

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * 0"
      timezone: "America/Chicago"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run TMDB ingestion
        env:
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PAT: ${{ secrets.SNOWFLAKE_PAT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

        run: python python/main.py

      - name: Trigger dbt production job
        env:
          DBT_API_TOKEN: ${{ secrets.DBT_API_TOKEN }}
          DBT_ACCOUNT_ID: ${{ secrets.DBT_ACCOUNT_ID }}
          DBT_JOB_ID: ${{ secrets.DBT_JOB_ID }}

        run: python python/dbt_run_monitor.py
